### ISSUE TITLE
SailsJS crashing with "Callback called multiple times"

### ISSUE THREAD

**Issue by Yokutto** [texh/skipper-minio#2]
When I set the upload config to use one or more validations such as allowedFileTypes and maxBytes, SailsJS will crash with error:
```
error: Sending 500 ("Server Error") response: 
 Upload Error: Uploaded file 10mb.bin of type application/octet-stream is not allowed
    at onMimeDetected ([REDACTED]/node_modules/skipper-minio/standalone/build-mime-intercept-stream.js:83:19)
    at Object.<anonymous> ([REDACTED]/node_modules/skipper-minio/standalone/build-mime-intercept-stream.js:63:7)
_stream_writable.js:415
    throw new ERR_MULTIPLE_CALLBACK();
    ^

Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
    at onwrite (_stream_writable.js:415:11)
    at Transform.<anonymous> ([REDACTED]/node_modules/skipper-minio/standalone/build-minio-receiver-stream.js:141:7)
    at Transform.emit (events.js:315:20)
    at Transform.EventEmitter.emit (domain.js:485:12)
    at [REDACTED]/node_modules/skipper-minio/standalone/gc.js:10:19
    at [REDACTED]/node_modules/skipper-minio/index.js:72:16
    at ClientRequest.<anonymous> ([REDACTED]/node_modules/minio/dist/main/minio.js:525:11)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:479:22)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:297:12) {
  code: 'ERR_MULTIPLE_CALLBACK'
}
```

I use "sails-hook-uploads" package to handle upload pointing to skipper-minio adapter, and here's my code:

```javascript
let { success, payloadTooLarge, invalidMimeType } = exits;
let file = req.file('something');

return await sails
  .uploadOne(file, {
    adapter: require('skipper-minio'),
    accessKey: '[REDACTED]',
    secretKey: '[REDACTED]',
    bucket: '[REDACTED]',
    endPoint: '[REDACTED]',
    region: '[REDACTED]',
    maxBytes: 1024 * 1024, // 10 mbytes
    allowedFileTypes: ['image/gif'],
  })
  .then((file) => {
    return success({ file });
  })
  .catch({ code: 'E_EXCEEDS_UPLOAD_LIMIT' }, (e) => {
    return payloadTooLarge(e);
  })
  .catch({ code: 'E_INVALID_FILE_TYPE' }, (e) => {
    return invalidMimeType(e);
  });
```

**Comment by nahanil** [comment]
Please share a stack trace and your code or a reproduction of the error in a repo or there's nothing I can do to help.

**Comment by Yokutto** [comment]
> Please share a stack trace and your code or a reproduction of the error in a repo or there's nothing I can do to help.

Sorry, I miss clicked Ctrl + Enter and the issue has been submited without context. I was not expecting a fast reply lol

I edited the issue with description with the stack and code used

**Comment by nahanil** [comment]
Sorry! I got excited.

Can confirm critical boom boom. Let me have a tinker.

**Comment by nahanil** [comment]
Let me know if 0.2.0 brings happier times

![bitmoji](https://sdk.bitmoji.com/render/panel/8c15569e-920d-40ca-a005-52d026c9bde5-b19341a1-bb64-4670-a6f6-09f0b426480d-v1.png?transparent=1&palette=1&width=246)

**Comment by Yokutto** [comment]
Hey,
It's a bit late to say but, it's working now :p 
Thanks for the fix !! :D

**Comment by nahanil** [comment]
Awesome! Thanks @Yokutto
